export const WILL_ABI = {
  address: "0xca3c5fd65c433ab2a6c4398dc6b9a70ba99723074f5a248262635ec5bcb8fe73",
  name: "will",
  friends: [],
  exposed_functions: [
    {
      name: "initialize_will",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "deposit",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "set_recipient",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "claim",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "get_balance",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "get_will_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["address", "address", "u64"],
    },
    {
      name: "will_exists",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "get_recipient",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["address"],
    },
    {
      name: "get_owner",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["address"],
    },
  ],
  structs: [
    {
      name: "Will",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        { name: "owner", type: "address" },
        { name: "recipient", type: "address" },
        { name: "funds", type: "0x1::coin::Coin<0x1::aptos_coin::AptosCoin>" },
      ],
    },
  ],
} as const; 